#%RAML 1.0
title: Category System API

description: As a user, can access information about categories from the Caliber Legacy API

types:
  category: !include DataTypes/category.raml

/category:
  get:
    responses:
      200:
        body:
          application/json:
            type: category[]
            examples:
              output: !include Examples/categoryExample.raml

/category/{id}:
  uriParameters:
    id:
      required: true
      type: integer
  get:
    responses:
      200:
        body:
         application/json:
           type: category[]
           examples:
             output: !include Examples/categoryExample.raml
